import streamlit as st
import requests
import datetime
import sys


BASE_URL = "http://localhost:8000" # Backend endpoint


st.set_page_config(
    page_title= "🌎 Travel Planner Agentic Application",
    page_icon= "🌎",
    layout= "centered",
    initial_sidebar_state= "expanded",

)

st.title("🌎 Travel Planner Agentic Application")

#Initialize the chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display the chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input= st.text_input("User Input", placeholder="e.g Plan a trip to Goa for 5 days")
    submit_button= st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # Show user message
        # Show thinking spinner while backend processes the request
        with st.spinner("Bot is thinking..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")

            # Extract the direct text content, removing any wrapper like {'type': 'text', 'text': ...}
            if isinstance(answer, list) and len(answer) > 0:
                item = answer[0]
                if isinstance(item, dict) and 'text' in item:
                    direct_answer = item['text']
                else:
                    direct_answer = str(item)  # Fallback if not a dict with 'text'
            elif isinstance(answer, dict) and 'text' in answer:
                direct_answer = answer['text']
            else:
                direct_answer = str(answer)  # Fallback for plain string or other formats
        
            markdown_content = f""" # 🌎 AI Travel Plan

            ---

            {direct_answer}

            ---

            *This travel plan was generated by AI. Please verify all informations, especially prices, opening hours, and availability before making any bookings or travel arrangements.*
            """

            st.markdown(markdown_content)

        else:
            st.error("Bot failed to respond: " + response.text)
    
    except Exception as e:
        raise f"The response failed due to {e}"

