import os
import datetime

def save_document(response_text: str, directory: str = "./output"):
    """
    Export travel plan to Markdown file with proper formatting.
    """
    os.makedirs(directory, exist_ok=True)

    # Create markdowm content with metadata header
    markdown_content = f""" # 🌎 AI Travel Plan
    
    ---

    {response_text}

    ---

    *This travel plan was generated by AI. Please verify all informations, especially prices, opening hours, and availability before making any bookings or travel arrangements.*
    """
    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
        filename = f"{directory}/AI_Travel_Plan_{timestamp}.md"

        print(filename)

        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)

        print(f"Markdown file saved to: {filename}")
        return filename
    
    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None
          